### ISSUE TITLE
[Feature request] Add repository size to index

### ISSUE THREAD

**Issue by smacker** [src-d/datasets#27]
It would be very useful (at least for me) to have size of repository in bytes in csv file.

**Comment by bzz** [comment]
\cc @vmarkovtsev @ajnavarro for triage

**Comment by vmarkovtsev** [comment]
I am +1

**Comment by campoy** [comment]
That's a good idea, indeed. From the pga tool point of view there's no problem adding this extra piece of information.

I think the hard part is going to be adding this data into the index.

**Comment by mcarmonaa** [comment]
I've been having a look at this and I ran into a couple of question/problems:

- the required size, is it the original repository's size?
If so, it's not easy to include that info in the index. The repositories are downloaded by borges, aggregated in rooted repos and archived in siva files. Therefore that information isn't collected in any form. To get the original size, would we have to clone each repo again without making use of borges?

- the required size, is the size of the siva file?
if so, since repositories can be split into different rooted repositories (then into different siva files too) we can either add the size of each of the siva files needed to retrieve the complete repository or the sum of all of them so you'd know that as the most you have to download X bytes for a certain repository.

cc @src-d/data-retrieval

**Comment by smacker** [comment]
jfyi: You call GitHub api to get stars. In the response you also have "original size".

When I was creating the issue I most probably meant the size of sivas.
